import {
  Bell,
  Boxes,
  CalendarCheck,
  ClipboardList,
  Download,
  FileSpreadsheet,
  Gauge,
  Handshake,
  Landmark,
  type LucideIcon,
  MapPinned,
  Receipt,
  ScrollText,
  Star,
  Truck,
  UserRound,
  Workflow,
  Wrench,
} from 'lucide-react';
import type { FeatureKey } from '@solar/shared';

export const FEATURE_ICONS: Record<FeatureKey, LucideIcon> = {
  leads_crm: ClipboardList,
  site_survey: MapPinned,
  quotations: FileSpreadsheet,
  subsidy_loan: Landmark,
  inventory: Boxes,
  dispatch: Truck,
  net_metering: Gauge,
  expenses: Receipt,
  finance_dashboard: Gauge,
  partner_profit_split: Handshake,
  service_tickets: Wrench,
  amc_contracts: CalendarCheck,
  customer_portal: UserRound,
  google_reviews: Star,
  reports_export: Download,
  workflow_customisation: Workflow,
  audit_log: ScrollText,
  notifications: Bell,
};
